version: '3.8'

services:
  bot:
    build: .
    image: klutzco/lil-helper:latest
    restart: unless-stopped
    env_file:
      - .klutz.env
    environment:
      - DB_PATH=/app/data/lilhelper.db
    volumes:
      - data:/app/data
volumes:
  data:
    driver: local