version: '3.8'

services:
  bot:
    build: .
    image: klutzco/lil-helper:latest
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DB_PATH=/app/data/lilhelper.db
    volumes:
      - data:/app/data
volumes:
  data:
    driver: local